name: fine_merchant_mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  line_icons: ^2.0.1
  flutter_swiper: ^1.1.6
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.5
  cached_network_image: ^3.1.0
  curved_navigation_bar: ^1.0.3
  badges: ^3.1.1
  carousel_slider: ^4.0.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^6.1.5
  flutter_signin_button: ^2.0.0
  multiavatar: ^0.1.5
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.0.6
  provider: ^6.0.3
  get: ^4.1.4
  dio: ^5.3.2
  firebase_messaging: ^14.2.1
  scoped_model: ^2.0.0-nullsafety.0
  firebase_analytics: ^10.0.6
  firebase_dynamic_links: ^5.0.11
  introduction_screen: ^3.1.8
  flutter_icons: ^1.1.0
  intl: ^0.17.0
  reactive_forms: ^14.1.0
  shimmer: ^3.0.0
  flutter_neumorphic: ^3.2.0
  smooth_page_indicator: ^1.0.1
  logger: ^2.0.1
  scroll_to_index: ^3.0.1
  collection: ^1.17.0
  expandable: ^5.0.1
  animator: ^3.3.0
  # url_launcher: ^6.1.10

dependency_overrides:
  firebase_auth_platform_interface: 6.18.0
  firebase_messaging_platform_interface: 4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
